### ISSUE TITLE
what does the "art" in "l-artType" signify?

### ISSUE THREAD

**Issue by Conal-Tuohy** [Conal-Tuohy/TroveProxy#23]
What does "art" stand for? Article? Artifact? Art?

**Comment by Conal-Tuohy** [comment]
I note that if you query the Trove API including `facet=artType` you get a response which includes a display label which is simply `Type`

**Comment by mraadgev** [comment]
I'd say it's poor labeling, it looks like it's used to separate the Images, Maps and Objects category into Maps and everything else.

**Comment by Conal-Tuohy** [comment]
Just going to display the label "Type" for this field
