### ISSUE TITLE
Make `eac-cpf` inclusion optional?

### ISSUE THREAD

**Issue by Conal-Tuohy** [Conal-Tuohy/TroveProxy#9]
The `eac-cpf` inclusion does slow down processing and increase the size of the response (for responses which include people, at least).

Do we want to make this transclusion functionality optional. i.e. do we want people to be able to query for people records and not have the eac-cpf data transcluded? 

Certainly if you were just after a list of names, then the entire `eac-cpf` would be massive overkill.

If it were optional, what should be the default? We could require a `proxy-include-eac-cpf=true` parameter to make it happen, or require `proxy-include-eac-cpf=false` to make it _not_ happen.

**Comment by Conal-Tuohy** [comment]
As far the crosswalks are concerned, it would be probably be good to be prepared to process `<people>` records which have only the scanty data from the Trove API, and to make use of the `<eac-cpf>` data only if it's actually present.

**Comment by mraadgev** [comment]
Agreed that it should be optional, and I would be inclined to default it to not happening, particularly when there are more than one category present

**Comment by Conal-Tuohy** [comment]
fixed in 29fc077; users can include `proxy-include-people-australia=true` in the query URI to retrieve the `eac-cpf` data.
